# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nest C.I

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16]

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Install pnpm ⬇️'
      uses: pnpm/action-setup@v4
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: 'Install dependencies 📦'
      run: pnpm install

    - name: 'Prisma client'
      run: pnpm dlx prisma generate

    - name: 'build'
      run: pnpm run build

    - name: 'Test 🧪'
      env: 
        HASH: ${{ secrets.HASH }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pnpm run test